name: CI Project

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    deploy:
        runs-on: windows-latest
        strategy:
            matrix:
                node: [20.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: Install NPM
              run: npm install
            - name: Lint build
              run: npm run lint
            - name: Run unit test
              run: npm run test:unit
            - name: Storybook build
              run: npm run storybook:build
            - name: Run UI test
              run: npm run test:ui:ci
            - name: Build production
              run: npm run build
